version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bank-app:
    build: .
    container_name: bank-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-postgres:5432/transactions_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adminpassword
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - postgres-db
    networks:
      - bank-network
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge